### ISSUE TITLE
Inverted Keys

### ISSUE THREAD

**Issue by PanasMoti** [raylib-extras/extras-c#4]
The arrow keys are inverted -> up causes to look down, down causes to look up, right causes to turn left and left causes to turn right

i think it should be :
cam.ControlsKeys[6] = KEY_RIGHT;
cam.ControlsKeys[7] = KEY_LEFT;
cam.ControlsKeys[8] = KEY_DOWN;
cam.ControlsKeys[9] = KEY_UP;

**Comment by JeffM2501** [comment]
Yes, the math was backwards. The fix is to change the math, not reverse the keys. They keys need to match the Enums.
It has been fixed
